name: build

on:  
  workflow_call:
    inputs:
      reponame:
        required: true
        type: string




jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Hello User
        run: echo Hello, ${{ inputs.reponame }}

      - name: Checkout
        uses: actions/checkout@v3



   