name: build

on:  
  workflow_call:
    inputs:
      reponame:
        required: true
        type: string
      checkout:
        required: true
        type: string




jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Hello User
        run: echo Hello, ${{ inputs.reponame }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.checkout }}
          ref: dev
          fetch-depth: 0
          token: ${{ secrets.CICD_GITHUB_TOKEN }}


      - name: Git config 
        run: |          
          git config user.name "cicd"
          git config user.email "cicd@bala.com"
          echo "current git branch $(git rev-parse --abbrev-ref HEAD)"
          echo "current git user $(git config user.name)"      
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set gradle permissions 
        run: | 
          touch ${GITHUB_WORKSPACE}/local.properties
          chmod +x ./gradlew
          ./gradlew -v
          ./gradlew tasks
      - name: Set UTF-8 environment variable
        run: |
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
   