name: dispatch workflow

on:  
  workflow_dispatch:
    inputs:
      reponame:
        description: dispatch workflow
        required: true
        type: choice
        options: 
        - Blue

      checkout:
        description: checkout repo
        required: true
        type: choice
        options: 
        - balayml/android-blue





jobs:
  call-A:
    uses: balayml/android-cicd/.github/workflows/build.yaml@main
    with:
      reponame: ${{ inputs.reponame }}
      checkout: ${{ inputs.checkout }}
